// <auto-generated />
using System;
using CandyCoat.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CandyCoat.API.Migrations
{
    [DbContext(typeof(VenueDbContext))]
    [Migration("20260301000002_AddVenueConfig")]
    partial class AddVenueConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CandyCoat.API.Models.BookingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<int>("Gil")
                        .HasColumnType("integer");

                    b.Property<string>("PatronName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("VenueId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CandyCoat.API.Models.CosmeticSyncEntity", b =>
                {
                    b.Property<string>("CharacterHash")
                        .HasColumnType("text");

                    b.Property<byte[]>("BrotliBlob")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("CharacterHash");

                    b.HasIndex("VenueId");

                    b.ToTable("CosmeticsSync");
                });

            modelBuilder.Entity("CandyCoat.API.Models.EarningsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatronName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("VenueId");

                    b.ToTable("Earnings");
                });

            modelBuilder.Entity("CandyCoat.API.Models.GambaPresetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnnounceMacro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("DefaultMultiplier")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("GambaPresets");
                });

            modelBuilder.Entity("CandyCoat.API.Models.GlobalProfileEntity", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnType("text");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasChatTwoIntegrated")
                        .HasDefaultValue(false)
                        .HasColumnType("boolean");

                    b.Property<bool>("HasGlamourerIntegrated")
                        .HasDefaultValue(false)
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HomeWorld")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatronData")
                        .IsRequired()
                        .HasDefaultValue("{}")
                        .HasColumnType("text");

                    b.Property<string>("RegisteredVenues")
                        .IsRequired()
                        .HasDefaultValue("[]")
                        .HasColumnType("text");

                    b.Property<string>("StaffData")
                        .IsRequired()
                        .HasDefaultValue("{}")
                        .HasColumnType("text");

                    b.HasKey("ProfileId");

                    b.HasIndex("CharacterName");

                    b.ToTable("GlobalProfiles");
                });

            modelBuilder.Entity("CandyCoat.API.Models.PatronEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("BlacklistDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BlacklistFlaggedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BlacklistReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FavoriteDrink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RpHooks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalGilSpent")
                        .HasColumnType("integer");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.Property<int>("VisitCount")
                        .HasColumnType("integer");

                    b.Property<string>("World")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.HasIndex("VenueId", "Name")
                        .IsUnique();

                    b.ToTable("Patrons");
                });

            modelBuilder.Entity("CandyCoat.API.Models.PatronNoteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatronName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("VenueId");

                    b.ToTable("PatronNotes");
                });

            modelBuilder.Entity("CandyCoat.API.Models.RoomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OccupiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OccupiedSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatronName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("CandyCoat.API.Models.ServiceMenuEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("ServiceMenu");
                });

            modelBuilder.Entity("CandyCoat.API.Models.StaffEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeWorld")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDnd")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastHeartbeat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ShiftStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.HasIndex("VenueId", "CharacterName")
                        .IsUnique();

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("CandyCoat.API.Models.VenueConfigEntity", b =>
                {
                    b.Property<string>("VenueId")
                        .HasColumnType("text");

                    b.Property<bool>("ManagerPwAdded")
                        .HasDefaultValue(false)
                        .HasColumnType("boolean");

                    b.Property<string>("ManagerPw")
                        .IsRequired()
                        .HasDefaultValue("")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VenueId");

                    b.ToTable("VenueConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
